package oathdigital.gameplay.cards

import oathdigital.catalog.{Denizen, Edifice, ExecutableCatalog, Legacy, Relic, Site}
import oathdigital.catalog.holding._
import oathdigital.gameplay.operations.{HallOfMinistersCard,
  TheGrandScepterCard}
import oathdigital.gameplay.powers.action.{AlchemistCard, AmberFlameCard,
  ArcaneBrokersCard, ArmedMobCard, BallotBoxCard, BanditPaymasterCard,
  BarbedNetCard, BedOfRootsCard, BloodPactCard, BogCard, BoneDiceCard,
  BookOfRecordsCard, BrassHorseCard, CharmingFriendCard, ClayRattleCard,
  CrystalVialCard, DarkEnforcerCard, DemonTailCard, DowsingSticksCard,
  DreamThiefCard, EldersCard, EnchantressCard, FaeMerchantCard, FirebrandCard,
  GamblingHallCard, GreatFeastCard, HonorGuardCard, IvoryEyeCard, LevelersCard,
  MagicCarpetCard, MagicWaterskinCard, MemoryOfHomeCard, MemoryOfNatureCard,
  MessengerCard, OracleCard, OracularPigCard, PlagueEnginesCard, QuickExitCard,
  RelicBreakerCard, ScryerCard, SecondChanceCard, ShiftingMapCard,
  SiegeEnginesCard, SkeletonKeyCard, SleightOfHandCard, SpiritSnareCard,
  SpoiledSuppliesCard, StorytellerCard, TamingCharmCard, TavernSongsCard,
  TinkersFairCard, TutorCard, WaysideInnCard, WhisperingLeavesCard, WhistleCard,
  WizardSchoolCard, WolvesCard}
import oathdigital.gameplay.powers.campaign.{BagOfSiegeworksCard,
  BanditStandardCard, BannerBreakersCard, BattleAxesCard, BattleHonorsCard,
  BlackSwordCard, BookBurningCard, BrassArmyCard, CrackedSageCard,
  CrackingGroundCard, DisgracedCaptainCard, EncirclementCard,
  ExtraProvisionsCard, FearsomeShieldCard, FieldPromotionCard, FireTalkersCard,
  GarrisonArmoryCard, GleamingArmorCard, GreatCrusadeCard, HorseArchersCard,
  HospitalCard, InsectSwarmCard, LongbowsCard, MercenariesCard,
  MilitaryParadeCard, NatureWorshipCard, OutridersCard, PledgeOfDefenseCard,
  RainBootsCard, RivalKhanCard, StickyFireCard, StormCallerCard,
  TheGreatLevyCard, ToweringRampartCard, TributeSpoilsCard,
  VillageConstableCard, VowOfPeaceCard, WalledGardenCard, WarningSignalsCard,
  WatchdogCard, WrestlersCard}
import oathdigital.gameplay.powers.cardplay.{BookBindersCard, GossipCard,
  SacredGroundCard, SaddleMakersCard, SecretPoliceCard, VowOfObedienceCard,
  WelcomingPartyCard, WildCryCard}
import oathdigital.gameplay.powers.economy.{AnimalPlaymatesCard, BirdsongCard,
  CupOfPlentyCard, DowntroddenCard, InitiationRiteCard, KnightsErrantCard,
  RowdyPubCard, TheOldOakCard, VillageIdiotCard}
import oathdigital.gameplay.powers.recover.{CatacombsCard, RelicWorshipCard}
import oathdigital.gameplay.powers.rest.{InsomniaCard, LeagueTreatyCard,
  SilverTongueCard}
import oathdigital.gameplay.powers.search.{AuguryCard, CropRotationCard,
  DisciplesCard, TruthfulHarpCard}
import oathdigital.gameplay.powers.setup.{GreatForgeCard, GreatMarketCard,
  ProvingGroundsCard}
import oathdigital.gameplay.powers.targeting.{CircletOfCommandCard,
  ForgottenVaultCard, LostTongueCard, OakenFortressCard}
import oathdigital.gameplay.powers.title.ChaosCultCard
import oathdigital.gameplay.powers.travel.{DragonskinDrumCard, ForestPathsCard,
  GraspingVinesCard, RoyalStablesCard, TentsCard, TollRoadsCard}
import oathdigital.gameplay.powers.wake.{HornedMaskCard, HungerCard,
  MarbleFountainsCard, QuartermasterCard}
import oathdigital.gameplay.powers.whenplayed.{ASmallFavorCard, AnimalHostCard,
  BanditPrinceCard, CharlatanCard, DazzleCard, FabledFeastCard,
  FaithfulFriendCard, FamilyHeirloomCard, GarrisonCard, GreatHerdCard,
  KeyToTheCityCard, RiotsCard, RoyalTaxCard, SaladDaysCard, ShiftingFogCard,
  ThreateningRoarCard, TownMeetingCard, TwinBrotherCard}

/** Every printed New Foundations component, listed by kind in printed-id
  * order. A new card is added here and in its own file; `CardCatalogSuite`
  * pins the counts so a forgotten card fails a test.
  */
object NewFoundations:
  val denizens: Vector[Denizen] = Vector(
    WrestlersCard,
    MartialCultureCard,
    BanditChiefCard,
    ChaosCultCard,
    DefameCard,
    CodeOfHonorCard,
    OutridersCard,
    MessengerCard,
    FieldPromotionCard,
    PalanquinCard,
    ShieldWallCard,
    MilitaryParadeCard,
    ErrandBoyCard,
    TyrantCard,
    ForcedLaborCard,
    SecretPoliceCard,
    SpecialistCard,
    CaptainsCard,
    SiegeEnginesCard,
    RoyalTaxCard,
    TollRoadsCard,
    CurfewCard,
    MercenariesCard,
    KnightsErrantCard,
    VowOfObedienceCard,
    HuntingPartyCard,
    CouncilSeatCard,
    EncirclementCard,
    PeaceEnvoyCard,
    RelicHunterCard,
    HomesteadersCard,
    CropRotationCard,
    ARoundOfAleCard,
    TinkersFairCard,
    LandWardenCard,
    CharmingFriendCard,
    VillageConstableCard,
    FamilyHeirloomCard,
    NewsFromAfarCard,
    LevelersCard,
    FabledFeastCard,
    TheGreatLevyCard,
    HeartsAndMindsCard,
    RelicBreakerCard,
    RainBootsCard,
    BookBindersCard,
    BallotBoxCard,
    SaddleMakersCard,
    HeraldCard,
    RowdyPubCard,
    VowOfPeaceCard,
    DeedWriterCard,
    SaladDaysCard,
    MarriageCard,
    HospitalCard,
    ASmallFavorCard,
    AwaitedReturnCard,
    ConvoysCard,
    VowOfKinshipCard,
    WildMountsCard,
    LancersCard,
    MountainGiantCard,
    RivalKhanCard,
    LostTongueCard,
    SpecialEnvoyCard,
    ResettleCard,
    SecondWindCard,
    OracleCard,
    PilgrimageCard,
    SpellBreakerCard,
    MountedPatrolCard,
    GreatCrusadeCard,
    AncientBloodlineCard,
    AncientPactCard,
    StormCallerCard,
    FamilyWagonCard,
    WayStationCard,
    SleightOfHandCard,
    TwinBrotherCard,
    HospitalityCard,
    AFastSteedCard,
    RelicWorshipCard,
    NatureWorshipCard,
    BirdsongCard,
    SmallFriendsCard,
    GraspingVinesCard,
    ThreateningRoarCard,
    KeyToTheCityCard,
    FaeMerchantCard,
    SecondChanceCard,
    PiedPiperCard,
    MushroomsCard,
    InsectSwarmCard,
    VowOfUnionCard,
    GiantPythonCard,
    WarTortoiseCard,
    NewGrowthCard,
    WildCryCard,
    ScryerCard,
    AnimalHostCard,
    MemoryOfNatureCard,
    MarshSpiritCard,
    VowOfPovertyCard,
    ForestCouncilCard,
    WalledGardenCard,
    VowOfBeastkinCard,
    BrackenCard,
    WildAlliesCard,
    GolemLegionsCard,
    BattleHonorsCard,
    DisgracedCaptainCard,
    CouncilArbiterCard,
    CatacombsCard,
    WardOfSilenceCard,
    VowOfWisdomCard,
    ArcaneBrokersCard,
    DisciplesCard,
    ArcaneArmorCard,
    GlamorCard,
    WizardsConclaveCard,
    TrueOathCard,
    NaysayersCard,
    BogCard,
    WhisperingLeavesCard,
    BedOfRootsCard,
    AutumnWindCard,
    ShiftingFogCard,
    FaeBattalionCard,
    HungerCard,
    SignalTreesCard,
    ForestWardenCard,
    BanditPaymasterCard,
    BookBurningCard,
    ReliquaryRaidCard,
    TrackerCard,
    BannerBreakersCard,
    PledgeToDiscordCard,
    FriendlyFamiliarCard,
    UnstableSummonCard,
    BanditPrinceCard,
    DarkEnforcerCard,
    SpoiledSuppliesCard,
    OldSongsCard,
    AncientBindingCard,
    DiplomatCard,
    VillageIdiotCard,
    SpinningBeeCard,
    FirebrandCard,
    WatchdogCard,
    FavoredSonCard,
    TownMeetingCard,
    LeagueTreatyCard,
    SkilledMerchantsCard,
    TributeSpoilsCard,
    HorseArchersCard,
    SearchPartyCard,
    MovingMarketCard,
    TravelingNegotiatorCard,
    PledgeOfDefenseCard,
    TheRedSeerCard,
    RoyalStablesCard,
    CallForHelpCard,
    VowOfWanderingCard,
    MountedLibraryCard,
    MasterAtArmsCard,
    WarningSignalsCard,
    BaronCard,
    HonorGuardCard,
    CityWallCard,
    FearsomeGeneralCard,
    CarefulPlansCard,
    GarrisonArmoryCard,
    BattleAxesCard,
    GreatFeastCard,
    QuartermasterCard,
    EldersCard,
    TheGatheringCard,
    FaithfulFriendCard,
    TentsCard,
    BearTrapsCard,
    GreatHerdCard,
    FireTalkersCard,
    MagiciansCodeCard,
    SpiritSnareCard,
    WizardSchoolCard,
    DazzleCard,
    ActingTroupeCard,
    TamingCharmCard,
    InquisitorCard,
    WolvesCard,
    LongbowsCard,
    AnimalPlaymatesCard,
    TrueNamesCard,
    TheOldOakCard,
    ForestPathsCard,
    LongLostHeirCard,
    RangersCard,
    RovingTerrorCard,
    WaysideInnCard,
    ExtraProvisionsCard,
    MemoryOfHomeCard,
    KeepCard,
    WelcomingPartyCard,
    TravelingDoctorCard,
    StorytellerCard,
    ArmedMobCard,
    TavernSongsCard,
    SecretSignalCard,
    AuguryCard,
    RustingRayCard,
    QuickExitCard,
    BillowingFogCard,
    PressgangsCard,
    KindredWarriorsCard,
    TerrorSpellsCard,
    BloodPactCard,
    RevelationCard,
    ObservatoryCard,
    PlagueEnginesCard,
    GleamingArmorCard,
    BewitchCard,
    JinxCard,
    TutorCard,
    GarrisonCard,
    DreamThiefCard,
    CrackingGroundCard,
    SealingWardCard,
    InitiationRiteCard,
    VowOfSilenceCard,
    ForgottenVaultCard,
    MapLibraryCard,
    WitchsBargainCard,
    MasterOfDisguiseCard,
    CharlatanCard,
    ScoutsCard,
    AssassinCard,
    DowntroddenCard,
    BlackmailCard,
    CrackedSageCard,
    DissentCard,
    FalseProphetCard,
    VowOfDivisionCard,
    ZealotsCard,
    RoyalAmbitionsCard,
    SaltTheEarthCard,
    AlchemistCard,
    BeastTamerCard,
    RiotsCard,
    SilverTongueCard,
    GamblingHallCard,
    RelicThiefCard,
    EnchantressCard,
    InsomniaCard,
    SneakAttackCard,
    GossipCard)

  val relics: Vector[Relic] = Vector(
    StickyFireCard,
    CursedCauldronCard,
    BrassHorseCard,
    TruthfulHarpCard,
    GrandMaskCard,
    HornedMaskCard,
    CupOfPlentyCard,
    WhistleCard,
    DowsingSticksCard,
    CrackedHornCard,
    BanditCrownCard,
    RingOfDevotionCard,
    SkeletonKeyCard,
    OracularPigCard,
    CircletOfCommandCard,
    IvoryEyeCard,
    ShiftingMapCard,
    ObsidianCageCard,
    BookOfRecordsCard,
    DragonskinDrumCard,
    CrystalVialCard,
    AncientWritCard,
    PaintedTrumpetCard,
    BoneDiceCard,
    BrassArmyCard,
    ImperialSealCard,
    FearsomeShieldCard,
    SingingMaskCard,
    LostTapestryCard,
    BanditStandardCard,
    SilverCharmCard,
    AmberFlameCard,
    WineOfWelcomeCard,
    WhisperingStoneCard,
    BlackSwordCard,
    BarbedNetCard,
    BagOfSiegeworksCard,
    SecretTestamentCard,
    MagicCarpetCard,
    YewStaffCard,
    SpitefulMirrorCard,
    WeepingBannerCard,
    SigilOfTheEyeCard,
    SigilOfTheHeartCard,
    MagicWaterskinCard,
    DemonTailCard,
    ClayRattleCard,
    TheGrandScepterCard)

  val edifices: Vector[Edifice] = Vector(
    HallOfDebateCard,
    GreatMarketCard,
    GrandCanalCard,
    StoneBathsCard,
    AmberDoorsCard,
    GreatForgeCard,
    WildPasturesCard,
    SacredGroundCard,
    GiantsPathCard,
    TempleOfAncestorsCard,
    GreatSpireCard,
    GreatClockCard,
    UndergroundLibraryCard,
    StonePortalCard,
    MarbleFountainsCard,
    HallOfMinistersCard,
    RelicPatrolsCard,
    TomeGuardiansCard,
    TheTribunalCard,
    ToweringRampartCard,
    FestivalDistrictCard,
    ProvingGroundsCard,
    SpiralCastleCard,
    BoilingLakeCard,
    HiddenPassagesCard,
    HallowedSpringCard,
    SchoolOfVinesCard,
    OakenFortressCard,
    ForbiddenForestCard,
    ForestHornCard)

  val legacies: Vector[Legacy] = Vector(
    IronHandCard,
    ChroniclerCard,
    SteadfastCard,
    PeacemakerCard,
    TheNeedleCard,
    CircleOfSwordsCard,
    GreatArchitectCard,
    AncestralLandsCard,
    ScepterBearerCard,
    RoyalLineCard,
    KeeperOfOrderCard,
    GoldenKeyCard,
    WorldCrafterCard,
    MatchmakerCard,
    RevolutionaryCard,
    PopulistCard,
    RivalCard,
    TheStandardBearerCard,
    TheEarCard,
    HeirloomCard,
    HighPriestCard,
    SeerCard,
    ArbiterCard,
    TheBrightBeaconCard,
    OathsOfLoyaltyCard,
    ConspiratorCard,
    LightFingersCard,
    SecretSocietyCard,
    RuthlessCard,
    QuestToDistantLandsCard,
    WealthyCard,
    GatekeeperCard,
    BelovedCard,
    TheMouthCard,
    ReformerCard,
    PathfinderCard)

  val sites: Vector[Site] = Vector(
    AncientCitySite,
    BrokenPeaksSite,
    BuriedGiantSite,
    DeepWoodsSite,
    DesolateShoreSite,
    DunesSite,
    FairIsleSite,
    GoldenValleySite,
    GreatSlumSite,
    GreenShoreSite,
    HeadwatersSite,
    HiddenPlaceSite,
    MinesSite,
    NarrowPassSite,
    PaintedTowersSite,
    RiverbankSite,
    RockyCoastSite,
    SaltFlatsSite,
    ShroudedWoodsSite,
    SolitaryPillarSite,
    StandingStonesSite,
    SteppeSite,
    SunkenIslesSite,
    TidalMarshesSite)

  /** The production catalog. Each kind is sorted by printed id as a string,
    * the order the JSON loader produced; setup and tests rely on it. */
  val catalog: ExecutableCatalog = ExecutableCatalog(
    denizens.sortBy(_.id.value), relics.sortBy(_.id.value),
    edifices.sortBy(_.id.value), legacies.sortBy(_.id.value),
    sites.sortBy(_.id.value))
