package oathdigital.application

import oathdigital.model._

sealed trait GameCommand extends Product with Serializable
object GameCommand {
  final case class WithModifiers(command: GameCommand,
      ordered: Vector[OrderedRuleInvocation]) extends GameCommand
  final case class Begin(chronicle: Chronicle, orders: SetupOrders)
      extends GameCommand
  final case class StartWalker(procedure: StartableRef, start: StartPayload)
      extends GameCommand
  final case class ResolveWalker(actor: PlayerId, treeDecision: TreeDecision)
      extends GameCommand
  /** Requests an authoritative app-layer roll for the currently parked pool.
    * Faces are generated by DefenseDicePort and enter the rules layer only
    * after the command has been validated.
    *
    * `actor` is the requester bound by the transport, checked against the
    * durable parked position's own actor by `OathRules.walkerResumeContext`
    * before anything is applied -- see C1: without it any authenticated
    * player in the game could resume another player's parked walker.
    */
  final case class RollWalker(actor: PlayerId, pool: PoolKey) extends GameCommand
  final case class EndWake(playerId: PlayerId) extends GameCommand
  final case class PeekSiteRelics(playerId: PlayerId) extends GameCommand
  final case class RevealOwnedRelic(playerId: PlayerId, relic: RelicId)
      extends GameCommand
  final case class MoveWarbands(playerId: PlayerId, toSite: Boolean, amount: Int)
      extends GameCommand
  final case class BeginRest(playerId: PlayerId) extends GameCommand
  final case class FinishRest(playerId: PlayerId) extends GameCommand
  final case class UsePower(playerId: PlayerId, power: PowerId,
      source: DecisionOptionRef) extends GameCommand
}

/** Generic action-start data. Action-specific starts may widen this family
  * when another walker procedure needs more than its actor.
  *
  * `modifiers` (Task 4) is the ordered list of player-selected power ids the
  * client chose before starting the action -- e.g. answering Recover's
  * `RecoverModifierSelection` window. An empty vector means "no modifiers",
  * which is every walker Recover today; `OathRules.startWalker` validates
  * every id against the audited catalog before walking.
  */
/** `startArgs` (batch-1 Task 5) is what the player selected before the
  * action started, for an action whose tree needs it -- Travel's destination
  * is the only one today. They are the same `DecisionOptionRef`s a decision
  * option names, and the command layer does not interpret them:
  * `OathRules.startWalker` hands them to the registered action's own builder,
  * which rejects a shape it did not ask for. Empty is every Recover and every
  * Forge.
  */
final case class StartPayload(actor: PlayerId,
    modifiers: Vector[PowerId] = Vector.empty,
    startArgs: Vector[DecisionOptionRef] = Vector.empty)

/** One answer to the currently parked generic walker decision. */
final case class TreeDecision(decisionId: String, answer: DecisionAnswer)
