package oathdigital.application

import oathdigital.gameplay.{OrderedRuleInvocation, TradeResource}
import oathdigital.gameplay.setup.FirstGameSetupPlan
import oathdigital.model._

sealed trait GameCommand extends Product with Serializable
object GameCommand {
  final case class WithModifiers(command: GameCommand,
      ordered: Vector[OrderedRuleInvocation]) extends GameCommand
  final case class Begin(plan: FirstGameSetupPlan) extends GameCommand
  final case class StartWalker(procedure: StartableRef, start: StartPayload)
      extends GameCommand
  final case class ResolveWalker(actor: PlayerId, treeDecision: TreeDecision)
      extends GameCommand
  /** Requests an authoritative app-layer roll for the currently parked pool.
    * Faces are generated by DefenseDicePort and enter the rules layer only
    * after the command has been validated.
    *
    * `actor` is the requester bound by the transport, checked against the
    * durable parked position's own actor by `OathRules.walkerResumeContext`
    * before anything is applied -- see C1: without it any authenticated
    * player in the game could resume another player's parked walker.
    */
  final case class RollWalker(actor: PlayerId, pool: PoolKey) extends GameCommand
  final case class PlacePawn(playerId: PlayerId, siteId: SiteId)
      extends GameCommand
  /** Internal setup adapter retained for rules tests; transports use ResolveCardDecision. */
  final case class ChooseAdviser(playerId: PlayerId, adviserId: DenizenId)
      extends GameCommand
  final case class EndWake(playerId: PlayerId) extends GameCommand
  final case class Muster(playerId: PlayerId, target: EconomyTargetRef)
      extends GameCommand
  final case class Trade(playerId: PlayerId, target: EconomyTargetRef,
      resource: TradeResource) extends GameCommand
  final case class BeginSearch(playerId: PlayerId, source: SearchSource)
      extends GameCommand
  final case class BeginChallenge(playerId: PlayerId, banner: Banner) extends GameCommand
  final case class ChooseChallengeSecretSite(playerId: PlayerId, decision: DecisionId,
      site: SiteId) extends GameCommand
  final case class CompleteChallenge(playerId: PlayerId, decision: DecisionId,
      amount: Int) extends GameCommand
  final case class PlaceBannerResource(playerId: PlayerId, banner: Banner,
      amount: Int) extends GameCommand
  final case class ResolveFacedownAdviser(playerId: PlayerId, adviser: WorldCardId,
      placement: Option[SearchPlacement]) extends GameCommand
  final case class PeekSiteRelics(playerId: PlayerId) extends GameCommand
  final case class RevealOwnedRelic(playerId: PlayerId, relic: RelicId)
      extends GameCommand
  final case class MoveWarbands(playerId: PlayerId, toSite: Boolean, amount: Int)
      extends GameCommand
  final case class RevealVision(playerId: PlayerId, visionId: VisionId)
      extends GameCommand
  final case class PlayConspiracy(playerId: PlayerId,
      target: Option[ConspiracyTargetRef]) extends GameCommand
  final case class BeginNegotiation(playerId: PlayerId,
      participants: Vector[PlayerId]) extends GameCommand
  final case class ReplaceNegotiationTerms(playerId: PlayerId,
      decision: DecisionId, terms: NegotiationTerms) extends GameCommand
  final case class AcceptNegotiation(playerId: PlayerId, decision: DecisionId)
      extends GameCommand
  final case class DeclineNegotiation(playerId: PlayerId, decision: DecisionId)
      extends GameCommand
  final case class BeginCampaignConquest(playerId: PlayerId, targetSiteIds: Vector[SiteId],
      attackDiceCount: Int) extends GameCommand
  final case class BeginCampaignRaid(playerId: PlayerId,
      targets: Vector[CampaignRaidTarget], attackDiceCount: Int) extends GameCommand
  object BeginCampaignConquest {
    def apply(playerId: PlayerId, targetSiteId: SiteId,
        attackDiceCount: Int): BeginCampaignConquest =
      new BeginCampaignConquest(playerId, Vector(targetSiteId), attackDiceCount)
  }
  final case class ChooseCampaignPlan(playerId: PlayerId, decision: DecisionId,
      source: PendingProcedure.CampaignPlanSource) extends GameCommand
  final case class FinishCampaignPlans(playerId: PlayerId, decision: DecisionId)
      extends GameCommand
  final case class ChooseCampaignSacrifice(playerId: PlayerId, decision: DecisionId,
      count: Int) extends GameCommand
  final case class PlaceCampaignForce(playerId: PlayerId, decision: DecisionId,
      allocations: Vector[CampaignForceAllocation]) extends GameCommand
  final case class RelocateCampaignRaidPawn(playerId: PlayerId,
      decision: DecisionId, destinationSiteId: SiteId) extends GameCommand
  /** Internal Search adapter retained for rules tests; transports use ResolveCardDecision. */
  final case class CompleteSearch(
      playerId: PlayerId,
      decision: DecisionId,
      kept: WorldCardId,
      discardedInOrder: Vector[WorldCardId],
      placement: SearchPlacement
  ) extends GameCommand
  final case class ResolveCardDecision(
      playerId: PlayerId,
      decision: DecisionId,
      resolution: CardDecisionResolution
  ) extends GameCommand
  final case class BeginRest(playerId: PlayerId) extends GameCommand
  final case class FinishRest(playerId: PlayerId) extends GameCommand
  final case class UsePower(playerId: PlayerId, power: PowerId,
      source: DecisionOptionRef) extends GameCommand
}

/** Generic action-start data. Action-specific starts may widen this family
  * when another walker procedure needs more than its actor.
  *
  * `modifiers` (Task 4) is the ordered list of player-selected power ids the
  * client chose before starting the action -- e.g. answering Recover's
  * `RecoverModifierSelection` window. An empty vector means "no modifiers",
  * which is every walker Recover today; `OathRules.startWalker` validates
  * every id against the audited catalog before walking.
  */
/** `startArgs` (batch-1 Task 5) is what the player selected before the
  * action started, for an action whose tree needs it -- Travel's destination
  * is the only one today. They are the same `DecisionOptionRef`s a decision
  * option names, and the command layer does not interpret them:
  * `OathRules.startWalker` hands them to the registered action's own builder,
  * which rejects a shape it did not ask for. Empty is every Recover and every
  * Forge.
  */
final case class StartPayload(actor: PlayerId,
    modifiers: Vector[PowerId] = Vector.empty,
    startArgs: Vector[DecisionOptionRef] = Vector.empty)

/** One answer to the currently parked generic walker decision. */
final case class TreeDecision(decisionId: String, answer: DecisionAnswer)

sealed trait CardDecisionResolution extends Product with Serializable
object CardDecisionResolution {
  final case class StartingAdviser(adviserId: DenizenId)
      extends CardDecisionResolution
  final case class Search(
      kept: WorldCardId,
      discardedInOrder: Vector[WorldCardId],
      placement: SearchPlacement
  ) extends CardDecisionResolution
}
